### ISSUE TITLE
Resize when input is not 576x1024

### ISSUE THREAD

**Issue by yosun** [replicate/cog-svd#6]
Why not include a input size checker / resizer

> WARNING: The conditioning frame you provided is not 576x1024. This leads to suboptimal performance as model was only trained on 576x1024. Consider increasing `cond_aug`.

**Comment by fofr** [comment]
There are the current resize options:

<img width="331" alt="Screenshot 2023-11-29 at 21 43 55" src="https://github.com/replicate/cog-svd/assets/319055/14aaa889-7660-485c-a3fd-ba81b86a71ab">

1. Will resize to as close as 1024x576 while maintaining aspect ratio
2. Will resize down then crop to exactly 1024x576
3. Uses the image size

**Comment by yosun** [comment]
i think that in this case, the sizing strategy does not make sense, as the video generation seems to only work when 16:9
